// Code generated by scapi/gen. DO NOT EDIT.
package contractsapi

import (
	"github.com/0xPolygon/polygon-edge/types"
)

type InitializeBridgeContractFn struct {
	MaxNumberOfTransactions uint16 `abi:"_maxNumberOfTransactions"`
	TimeoutBlocksNumber     uint8  `abi:"_timeoutBlocksNumber"`
}

func (i *InitializeBridgeContractFn) Sig() []byte {
	return BridgeContract.Abi.Methods["initialize"].ID()
}

func (i *InitializeBridgeContractFn) EncodeAbi() ([]byte, error) {
	return BridgeContract.Abi.Methods["initialize"].Encode(i)
}

func (i *InitializeBridgeContractFn) DecodeAbi(buf []byte) error {
	return decodeMethod(BridgeContract.Abi.Methods["initialize"], buf, i)
}

type InitializeClaimsHelperFn struct {
	SignedBatchManagerAddress types.Address `abi:"_signedBatchManagerAddress"`
}

func (i *InitializeClaimsHelperFn) Sig() []byte {
	return ClaimsHelper.Abi.Methods["initialize"].ID()
}

func (i *InitializeClaimsHelperFn) EncodeAbi() ([]byte, error) {
	return ClaimsHelper.Abi.Methods["initialize"].Encode(i)
}

func (i *InitializeClaimsHelperFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ClaimsHelper.Abi.Methods["initialize"], buf, i)
}

type InitializeClaimsManagerFn struct {
	BridgeContract            types.Address `abi:"_bridgeContract"`
	ClaimsHelper              types.Address `abi:"_claimsHelper"`
	ValidatorsContract        types.Address `abi:"_validatorsContract"`
	SignedBatchManagerAddress types.Address `abi:"_signedBatchManagerAddress"`
}

func (i *InitializeClaimsManagerFn) Sig() []byte {
	return ClaimsManager.Abi.Methods["initialize"].ID()
}

func (i *InitializeClaimsManagerFn) EncodeAbi() ([]byte, error) {
	return ClaimsManager.Abi.Methods["initialize"].Encode(i)
}

func (i *InitializeClaimsManagerFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ClaimsManager.Abi.Methods["initialize"], buf, i)
}

type InitializeSignedBatchManagerFn struct {
	BridgeContract types.Address `abi:"_bridgeContract"`
}

func (i *InitializeSignedBatchManagerFn) Sig() []byte {
	return SignedBatchManager.Abi.Methods["initialize"].ID()
}

func (i *InitializeSignedBatchManagerFn) EncodeAbi() ([]byte, error) {
	return SignedBatchManager.Abi.Methods["initialize"].Encode(i)
}

func (i *InitializeSignedBatchManagerFn) DecodeAbi(buf []byte) error {
	return decodeMethod(SignedBatchManager.Abi.Methods["initialize"], buf, i)
}

type InitializeSlotsManagerFn struct {
	BridgeContractAddress types.Address `abi:"_bridgeContractAddress"`
	ValidatorsContract    types.Address `abi:"_validatorsContract"`
}

func (i *InitializeSlotsManagerFn) Sig() []byte {
	return SlotsManager.Abi.Methods["initialize"].ID()
}

func (i *InitializeSlotsManagerFn) EncodeAbi() ([]byte, error) {
	return SlotsManager.Abi.Methods["initialize"].Encode(i)
}

func (i *InitializeSlotsManagerFn) DecodeAbi(buf []byte) error {
	return decodeMethod(SlotsManager.Abi.Methods["initialize"], buf, i)
}

type InitializeUTXOsManagerFn struct {
	BridgeContractAddress types.Address `abi:"_bridgeContractAddress"`
	ClaimsManagerAddress  types.Address `abi:"_claimsManagerAddress"`
}

func (i *InitializeUTXOsManagerFn) Sig() []byte {
	return UTXOsManager.Abi.Methods["initialize"].ID()
}

func (i *InitializeUTXOsManagerFn) EncodeAbi() ([]byte, error) {
	return UTXOsManager.Abi.Methods["initialize"].Encode(i)
}

func (i *InitializeUTXOsManagerFn) DecodeAbi(buf []byte) error {
	return decodeMethod(UTXOsManager.Abi.Methods["initialize"], buf, i)
}

type InitializeValidatorsContractFn struct {
	Validators            []types.Address `abi:"_validators"`
	BridgeContractAddress types.Address   `abi:"_bridgeContractAddress"`
}

func (i *InitializeValidatorsContractFn) Sig() []byte {
	return ValidatorsContract.Abi.Methods["initialize"].ID()
}

func (i *InitializeValidatorsContractFn) EncodeAbi() ([]byte, error) {
	return ValidatorsContract.Abi.Methods["initialize"].Encode(i)
}

func (i *InitializeValidatorsContractFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ValidatorsContract.Abi.Methods["initialize"], buf, i)
}
