// Code generated by scapi/gen. DO NOT EDIT.
package contractsapi

import (
	"github.com/0xPolygon/polygon-edge/types"
)

type InitializeBridgeContractFn struct {
}

func (i *InitializeBridgeContractFn) Sig() []byte {
	return BridgeContract.Abi.Methods["initialize"].ID()
}

func (i *InitializeBridgeContractFn) EncodeAbi() ([]byte, error) {
	return BridgeContract.Abi.Methods["initialize"].Encode(i)
}

func (i *InitializeBridgeContractFn) DecodeAbi(buf []byte) error {
	return decodeMethod(BridgeContract.Abi.Methods["initialize"], buf, i)
}

type SetDependenciesBridgeContractFn struct {
	ClaimsAddress        types.Address `abi:"_claimsAddress"`
	SignedBatchesAddress types.Address `abi:"_signedBatchesAddress"`
	SlotsAddress         types.Address `abi:"_slotsAddress"`
	UtxoscAddress        types.Address `abi:"_utxoscAddress"`
	ValidatorsAddress    types.Address `abi:"_validatorsAddress"`
}

func (s *SetDependenciesBridgeContractFn) Sig() []byte {
	return BridgeContract.Abi.Methods["setDependencies"].ID()
}

func (s *SetDependenciesBridgeContractFn) EncodeAbi() ([]byte, error) {
	return BridgeContract.Abi.Methods["setDependencies"].Encode(s)
}

func (s *SetDependenciesBridgeContractFn) DecodeAbi(buf []byte) error {
	return decodeMethod(BridgeContract.Abi.Methods["setDependencies"], buf, s)
}

type InitializeClaimsHelperFn struct {
}

func (i *InitializeClaimsHelperFn) Sig() []byte {
	return ClaimsHelper.Abi.Methods["initialize"].ID()
}

func (i *InitializeClaimsHelperFn) EncodeAbi() ([]byte, error) {
	return ClaimsHelper.Abi.Methods["initialize"].Encode(i)
}

func (i *InitializeClaimsHelperFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ClaimsHelper.Abi.Methods["initialize"], buf, i)
}

type SetDependenciesClaimsHelperFn struct {
	ClaimsAddress        types.Address `abi:"_claimsAddress"`
	SignedBatchesAddress types.Address `abi:"_signedBatchesAddress"`
}

func (s *SetDependenciesClaimsHelperFn) Sig() []byte {
	return ClaimsHelper.Abi.Methods["setDependencies"].ID()
}

func (s *SetDependenciesClaimsHelperFn) EncodeAbi() ([]byte, error) {
	return ClaimsHelper.Abi.Methods["setDependencies"].Encode(s)
}

func (s *SetDependenciesClaimsHelperFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ClaimsHelper.Abi.Methods["setDependencies"], buf, s)
}

type InitializeClaimsManagerFn struct {
	MaxNumberOfTransactions uint16 `abi:"_maxNumberOfTransactions"`
	TimeoutBlocksNumber     uint8  `abi:"_timeoutBlocksNumber"`
}

func (i *InitializeClaimsManagerFn) Sig() []byte {
	return ClaimsManager.Abi.Methods["initialize"].ID()
}

func (i *InitializeClaimsManagerFn) EncodeAbi() ([]byte, error) {
	return ClaimsManager.Abi.Methods["initialize"].Encode(i)
}

func (i *InitializeClaimsManagerFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ClaimsManager.Abi.Methods["initialize"], buf, i)
}

type SetDependenciesClaimsManagerFn struct {
	BridgeAddress       types.Address `abi:"_bridgeAddress"`
	ClaimsHelperAddress types.Address `abi:"_claimsHelperAddress"`
	Utxosc              types.Address `abi:"_utxosc"`
	ValidatorsAddress   types.Address `abi:"_validatorsAddress"`
}

func (s *SetDependenciesClaimsManagerFn) Sig() []byte {
	return ClaimsManager.Abi.Methods["setDependencies"].ID()
}

func (s *SetDependenciesClaimsManagerFn) EncodeAbi() ([]byte, error) {
	return ClaimsManager.Abi.Methods["setDependencies"].Encode(s)
}

func (s *SetDependenciesClaimsManagerFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ClaimsManager.Abi.Methods["setDependencies"], buf, s)
}

type InitializeSignedBatchManagerFn struct {
}

func (i *InitializeSignedBatchManagerFn) Sig() []byte {
	return SignedBatchManager.Abi.Methods["initialize"].ID()
}

func (i *InitializeSignedBatchManagerFn) EncodeAbi() ([]byte, error) {
	return SignedBatchManager.Abi.Methods["initialize"].Encode(i)
}

func (i *InitializeSignedBatchManagerFn) DecodeAbi(buf []byte) error {
	return decodeMethod(SignedBatchManager.Abi.Methods["initialize"], buf, i)
}

type SetDependenciesSignedBatchManagerFn struct {
	BridgeAddress       types.Address `abi:"_bridgeAddress"`
	ClaimsHelperAddress types.Address `abi:"_claimsHelperAddress"`
	ValidatorsAddress   types.Address `abi:"_validatorsAddress"`
}

func (s *SetDependenciesSignedBatchManagerFn) Sig() []byte {
	return SignedBatchManager.Abi.Methods["setDependencies"].ID()
}

func (s *SetDependenciesSignedBatchManagerFn) EncodeAbi() ([]byte, error) {
	return SignedBatchManager.Abi.Methods["setDependencies"].Encode(s)
}

func (s *SetDependenciesSignedBatchManagerFn) DecodeAbi(buf []byte) error {
	return decodeMethod(SignedBatchManager.Abi.Methods["setDependencies"], buf, s)
}

type InitializeSlotsManagerFn struct {
}

func (i *InitializeSlotsManagerFn) Sig() []byte {
	return SlotsManager.Abi.Methods["initialize"].ID()
}

func (i *InitializeSlotsManagerFn) EncodeAbi() ([]byte, error) {
	return SlotsManager.Abi.Methods["initialize"].Encode(i)
}

func (i *InitializeSlotsManagerFn) DecodeAbi(buf []byte) error {
	return decodeMethod(SlotsManager.Abi.Methods["initialize"], buf, i)
}

type SetDependenciesSlotsManagerFn struct {
	BridgeAddress     types.Address `abi:"_bridgeAddress"`
	ValidatorsAddress types.Address `abi:"_validatorsAddress"`
}

func (s *SetDependenciesSlotsManagerFn) Sig() []byte {
	return SlotsManager.Abi.Methods["setDependencies"].ID()
}

func (s *SetDependenciesSlotsManagerFn) EncodeAbi() ([]byte, error) {
	return SlotsManager.Abi.Methods["setDependencies"].Encode(s)
}

func (s *SetDependenciesSlotsManagerFn) DecodeAbi(buf []byte) error {
	return decodeMethod(SlotsManager.Abi.Methods["setDependencies"], buf, s)
}

type InitializeUTXOsManagerFn struct {
}

func (i *InitializeUTXOsManagerFn) Sig() []byte {
	return UTXOsManager.Abi.Methods["initialize"].ID()
}

func (i *InitializeUTXOsManagerFn) EncodeAbi() ([]byte, error) {
	return UTXOsManager.Abi.Methods["initialize"].Encode(i)
}

func (i *InitializeUTXOsManagerFn) DecodeAbi(buf []byte) error {
	return decodeMethod(UTXOsManager.Abi.Methods["initialize"], buf, i)
}

type SetDependenciesUTXOsManagerFn struct {
	BridgeAddress types.Address `abi:"_bridgeAddress"`
	ClaimsAddress types.Address `abi:"_claimsAddress"`
}

func (s *SetDependenciesUTXOsManagerFn) Sig() []byte {
	return UTXOsManager.Abi.Methods["setDependencies"].ID()
}

func (s *SetDependenciesUTXOsManagerFn) EncodeAbi() ([]byte, error) {
	return UTXOsManager.Abi.Methods["setDependencies"].Encode(s)
}

func (s *SetDependenciesUTXOsManagerFn) DecodeAbi(buf []byte) error {
	return decodeMethod(UTXOsManager.Abi.Methods["setDependencies"], buf, s)
}

type InitializeValidatorsContractFn struct {
	Validators []types.Address `abi:"_validators"`
}

func (i *InitializeValidatorsContractFn) Sig() []byte {
	return ValidatorsContract.Abi.Methods["initialize"].ID()
}

func (i *InitializeValidatorsContractFn) EncodeAbi() ([]byte, error) {
	return ValidatorsContract.Abi.Methods["initialize"].Encode(i)
}

func (i *InitializeValidatorsContractFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ValidatorsContract.Abi.Methods["initialize"], buf, i)
}

type SetDependenciesValidatorsContractFn struct {
	BridgeAddress types.Address `abi:"_bridgeAddress"`
}

func (s *SetDependenciesValidatorsContractFn) Sig() []byte {
	return ValidatorsContract.Abi.Methods["setDependencies"].ID()
}

func (s *SetDependenciesValidatorsContractFn) EncodeAbi() ([]byte, error) {
	return ValidatorsContract.Abi.Methods["setDependencies"].Encode(s)
}

func (s *SetDependenciesValidatorsContractFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ValidatorsContract.Abi.Methods["setDependencies"], buf, s)
}
